# Gradle
# Build your Java project and run tests with Gradle using a Gradle wrapper script.
# Add steps that analyze code, save build artifacts, deploy, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/java

trigger:
- main

pool:
  vmImage: ubuntu-latest

steps:

- task: Gradle@2
  inputs:
    workingDirectory: ''
    gradleWrapperFile: 'gradlew'
    gradleOptions: '-Xmx3072m'
    javaHomeOption: 'JDKVersion'
    jdkVersionOption: '1.11'
    jdkArchitectureOption: 'x64'
    publishJUnitResults: true
    testResultsFiles: '**/TEST-*.xml'
    tasks: 'build'

- task: Bash@3
  inputs:
    targetType: 'inline'
    script: |
      # Fortify SCA Setup without plugin
      echo "Installing Fortify SCA"
      if sourceanalyzer -version >dev/null 2>&1; then
        echo "Fortify is alerady installed"
      else
        # Creating temporary and final directory structures
        mkdir /tmp/Fortify
        mkdir /opt/Fortify
        chmod --silent -R 775 /opt/Fortify
        cd /tmp/Fortify      
        
        # Download binaries from SSC
        curl -OLS "https://$(SERVER_IP):8443/ssc/downloads/{Fortify_SCA_and_Apps_22.1.0_linux_x64.run,fortify.license}"
        chmod --silent 775 Fortify_SCA_and_Apps_22.1.0_linux_x64.run
        
        # Run the Fortify SCA installer
        ./Fortify_SCA_and_Apps_22.1.0_linux_x64.run            \
        --mode unattended                                      \
        --installdir /opt/Fortify/Fortify_SCA_and_Apps_22      \
        --fortify_license_path /tmp/Fortify/fortify.license    \
        --MigrateSCA 0 --InstallSamples 0
        chmod--silent -R 775 /opt/Fortify/Fortify_SCA_and_Apps_22/bin
        
        /opt/Fortify/Fortify_SCA_and_Apps_22/bin/fortifyupdate
      fi
      enabled:false

- task: Bash@3
  inputs:
    targetType: 'inline'
    script: |
      # Fortify SCA Setup using plugin
      echo "Installing Fortify SCA"
            
      # Creating temporary and final directory structures
      mkdir /tmp/Fortify
      chmod --silent -R 775 /tmp/Fortify

      # Download binaries from SSC
      curl -OLS "https://$(SERVER_IP):8443/ssc/downloads/{Fortify_SCA_and_Apps_22.1.0_linux_x64.run,fortify.license}"
      chmod --silent 775

      enabled: true

- task: InstallFortifySCA@7
  inputs:
    InstallerPath: '/tmp/Fortify/Fortify_SCA_and_Apps_22.1.0_linux_x64.run'
    VS2015: false
    VS2022: true
    LicenseFile: '/tmp/Fortify/fortify.license'
    RunFortifyRulepackUpdate: true

- task: FortifyScanCentralSAST@7
  inputs:
    scanCentralCtrlUrl: 'https://$(SERVER_IP):10443/scancentral-ctrl'
    scanCentralClientToken: '$(ScanCentral.ClientToken)'
    sscUrl: 'https://$(SERVER_IP):8443/ssc'
    sscCiToken: '$(ScanCentral.SscCiToken)'
    uploadToSSC: true
    applicationName: 'Project-1'
    applicationVersion: 'Plugin-SC-G'
    timeoutForPollingArtifactState: 60
    buildTool: 'gradle'
    buildFile: 'build.gradle'
    block: true
    outputFile: 'scan.fpr'
    logFile: 'scn_log.fpr'